build: false

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda
    - PYTHON_VERSION: 3.4
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3
    - PYTHON_VERSION: 3.5
      PYTHON_ARCH: "64"
      MINICONDA: C:\Miniconda3

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pip mock h5py lxml nose numpy numba scipy scikit-image matplotlib pandas"
  - activate test-environment
  - pip install coverage
  - pip install pyFAI
  - pip install git+git://github.com/casimp/pyxpb
  - python setup.py install

test_script:
  - nosetests

on_success:
  # Could run coveralls here but will leave that to travis tests
  - echo Build succesful!